version: '3.1'
services:

  db:
    image: postgres:11.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345qw
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: coad
      PGPASSWORD: 12345qw
    volumes:
      - ../local-postgres-data:/var/lib/postgresql/data
      # - ../backups:/home
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: weslei.souza@amcom.com.br
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    depends_on:
      - db

  redis:
    image: redis:5.0.0-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  python:
    image: python:3.6-stretch
    container_name: python-coad


networks:
  default:
    external:
      name: coad-network

volumes:
  redisdata:
